#!/bin/bash
# install important programs and remove unimportant files
if [ -f "$HOME"/starter.sh ]; then
	rm "$HOME"/starter.sh
fi

sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install sudo -y
sudo apt-get install git curl wget zip tmux w3m vim podman fonts-inconsolata -y
sudo apt-get install firefox-esr feh gh -y
sudo apt-get remove nano libreoffice* -y
sudo apt-get remove gnome-games cheese evolution thunderbird rhythmbox shotwell -y
sudo apt-get autoremove -y
mkdir -p repos/github.com/$USER

# Consider installing newest versions of kitty terminal and neovim installed here
#software/kitty
#software/nvim-latest

sudo update-alternatives --install /usr/bin/www-browser www-browser /usr/bin/firefox-esr 210

rm ~/.bashrc
rm -rf ~/.vim
cat software/bashrc-loader >> ~/.bashrc
./setup-git
