#!/bin/bash	
git clone https://github.com/mskramst/mydotfiles
cd mydotfiles || exit
cp .bash_git .bashrc_ext .bash_aliases .bash_user .lang_aliases ~
rm -rf ~/.vim 
mv .vim ~
mv .config/kitty ~/.config
mv .config/tmux ~/.tmux

