#!/bin/bash	

git clone https://github.com/mskramst/mydotfiles
#add import to top of .bashrc by concatenating it with file and copying over
#sudo echo "if [ -f ~/.bashrc_ext ]; then . ~/.bashrc_ext; fi" \
#	| cat - ~/.bashrc > temp && mv temp ~/.bashrc
rm ~/.bashrc
cp software/bashrc ~/.bashrc
cd mydotfiles || exit
cp .bash_git .bashrc_ext ~
sudo mv --backup=simple .config ~
cd ~/.config/i3blocks || exit
git clone https://github.com/vivien/i3blocks-contrib
mv i3blocks-contrib scripts
#sudo mv kitty alacritty lynx vim tmux ~/.config


