#!/bin/bash
# add ssh to github account, must use gh auth login
git config --global init.defaultBranch main
git config --global user.email "" 
git config --global user.name "$USER"
echo -e "\ncopy key below into github ssh settings"
ssh-keygen -t ed25519 <<<~/.ssh/id_ed25519 && cat ~/.ssh/id_ed25519.pub
gh auth login -s admin:public_key

