#!/bin/bash
#config () {
#'/usr/bin/git --git-dir=$HOME/.cfg --work-tree=$HOME' 
#}

echo ".cfg" >> .gitignore
git clone --bare https://github.com/mskramst/mydotfiles "$HOME"/.cfg
git --git-dir="$HOME"/.cfg/ --work-tree="$HOME" checkout
#config config --local status.showUntrackedFiles no
git config --global init.defaultBranch main
git config --global user.email "" 
git config --global user.name "$USER"
echo -e "\ncopy key below into github ssh settings"
ssh-keygen -t ed25519 <<<~/.ssh/id_ed25519 && cat ~/.ssh/id_ed25519.pub
gh auth login -s admin:public_key

