#!/bin/bash
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install git curl wget zip tmux kitty w3m vim gh neovim podman fonts-inconsolata -y
sudo apt-get autoremove -y
mkdir -p repos/github.com/$USER

rm -rf ~/.config
rm ~/.bashrc
rm -rf ~/.vim
cat software/bashrc-loader >> ~/.bashrc

#config () {
#'/usr/bin/git --git-dir=$HOME/.cfg --work-tree=$HOME' 
#}

echo ".cfg" >> .gitignore
git clone --bare https://github.com/mskramst/mydotfiles $HOME/.cfg
git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout

