#!/bin/bash	
# install kitty terminal latest and kitten configurator
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
ln -s ~/.local/kitty.app/bin/kitty /usr/bin/kitty
ln -s ~/.local/kitty.app/bin/kitten /usr/bin/kitten
