#!/bin/bash

notes_directory="docs"
menu_options=("Create a new note" "List all notes" "Read a note" "Delete a note" "Exit")

# Function to create a new note
create_note() {
    echo "Enter the note content (Press Ctrl+D to save):"
    note_content=$(cat)
    echo "$note_content" > "$notes_directory/note_$(date +%Y%m%d%H%M%S).txt"
    echo "Note created successfully!"
}

# Function to list all notes
list_notes() {
    echo "Listing all notes:"
    ls -l "$notes_directory"
}

# Function to read a note
read_note() {
    list_notes
    echo "Enter the note filename to read:"
    read filename
    if [[ -f "$notes_directory/$filename" ]]; then
        echo "Note content:"
        cat "$notes_directory/$filename"
    else
        echo "Note not found."
    fi
}

# Function to delete a note
delete_note() {
    list_notes
    echo "Enter the note filename to delete:"
    read filename
    if [[ -f "$notes_directory/$filename" ]]; then
        rm "$notes_directory/$filename"
        echo "Note deleted successfully!"
    else
        echo "Note not found."
    fi
}

# Main menu loop
while true; do
    echo "----- Notes Menu -----"
    for i in "${!menu_options[@]}"; do
        echo "$((i+1)). ${menu_options[$i]}"
    done
    echo "----------------------"
    read -p "Enter your choice (1-${#menu_options[@]}): " choice

    case $choice in
        1)
            create_note
            ;;
         2)
            list_notes
            ;;
        3)
            read_note
            ;;
        4)
            delete_note
            ;;
        5)
            echo "Exiting..."
            break
            ;;
        *)
            echo "Invalid choice. Please enter a valid option."
            ;;
    esac

    echo
done

