#!/bin/bash

echo ".cfg" >> .gitignore
git clone --bare https://github.com/mskramst/mydotfiles $HOME/.cfg
git checkout --git-dir=$HOME/.cfg/ --work-tree=$HOME
git config --local status.showUntrackedFiles no
