#!/bin/bash

mkdir -p ~/repos/github.com/mskramst || exit
echo ".cfg" >> .gitignore
git clone --bare https://github.com/mskramst/mydotfiles $HOME/.cfg
git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout
config config --local status.showUntrackedFiles no
