#!/bin/bash

echo ".cfg" >> .gitignore
git clone --bare https://github.com/mskramst/mydotfiles $HOME/.cfg
git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout
git config --local status.showUntrackedFiles no
sudo echo "if [ -f ~/.bashrc_ext ]; then . ~/.bashrc_ext; fi" \
	| cat - ~/.bashrc > temp && mv temp ~/.bashrc
