#!/bin/bash

cd ~/repos/github.com/mskramst || exit
echo ".cfg" >> .gitignore
git clone --bare https://github.com/mskramst/mydotfiles $HOME/.cfg
git config --local status.showUntrackedFiles no
git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout
echo "if [ -f ~/.bashrc_ext ]; then . ~/.bashrc_ext; fi" >> ~/.bashrc
