TERM: xterm-256color

title: Alacritty

# Window class (Linux/BSD only):
class:
  # Application instance name
  instance: Alacritty
  # General application class
  general: Alacritty

scrolling:
  history: 5000

window:
  padding:
    x: 10
    y: 10

dynamic_padding: false

decorations: none

colors:
  # Default colors
  primary:
    background: '#0A0E14'
    foreground: '#B3B1AD'

  # Normal colors
  normal:
    black: '#01060E'
    red: '#EA6C73'
    green: '#91B362'
    yellow: '#F9AF4F'
    blue: '#5092d9'
    magenta: '#FAE994'
    cyan: '#90E1C6'
    white: '#C7C7C7'

  # Bright colors
  bright:
    black: '#686868'
    red: '#F07178'
    green: '#C2D94C'
    yellow: '#FFB454'
    blue: '#59C2FF'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'

font:
  family: Fira Code 
  size: 12.0

selection:
  text: '0x292d3e'
  background: '0xbbc5ff'

offset:
  x: 0
  y: 1

background_opacity: 1.0 

key_bindings:
  - key: C
    mods: Control|Shift
    action: Copy
  - key: P
    mods: Control|Shift
    action: Paste
  - key: W
    mods: Command
    action: ToggleFullscreen
  - key: N
    mods: Command|Shift
    action: SpawnNewInstance
  - key: F
    mods: Command|Shift
    action: ToggleFullscreen
  - key: Equals
    mods: Command|Shift
    action: IncreaseFontSize
  - key: Minus
    mods: Command|Shift
    action: DecreaseFontSize
  - key: Back
    mods: Super
    chars: "\x15"
  - key: Back
    mods: Control
    chars: "\x17"
  - key: Back
    mods: Alt
    chars: "\ed"
  - key: Left
    mods: Super
    chars: "\e[1;5D"
  - key: Right
    mods: Super
    chars: "\e[1;5C"
  - key: Left
    mods: Control
    chars: "\e[1;5D"
  - key: Right
    mods: Control
    chars: "\e[1;5C"
  - key: Left
    mods: Alt
    chars: "\e[1;5D"
  - key: Right
    mods: Alt
    chars: "\e[1;5C"
