#!/bin/bash	

#Theme Install
mkdir ~/.themes
mkdir ~/.local/share/icons
mkdir ~/Pictures/Wallpapers
mkdir ~/.fonts
git clone https://github.com/zayronxio/Zafiro-Nord-Dark
git clone https://github.com/EliverLara/Nordic
git clone https://github.com/yeyushengfan258/Future-cursors
wget https://raw.githubusercontent.com/EliverLara/Nordic/refs/heads/master/extras/wallpapers/nordic-wall.jpg
wget https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip
mv Nordic ~/.themes
mv Zafiro-Nord-Dark ~/.local/share/icons
mv Future-cursors ~/.local/share/icons
mv nordic-wall.jpg ~/Pictures/Wallpapers
mkdir JetBrains
unzip JetBrainsMono-2.304.zip JetBrains/
cd JetBrains/fonts/ttf || exit
unzip FiraCode.zip
mv FiraCode*.* ~/.fonts
mv *.* ~/.fonts

#App Install
sudo apt-get install plank polybar rofi
#git clone https://github.com/itsfoss/text-script-files.git
#mv -R text-script-files/config/polybar ~/.config
#cd ~/.config/polybar || exit
#sed -i 's/HDMI-1/Virtual1/g' config.ini
git clone https://github.com/catppuccin/rofi.git
mv rofi ~/.config
sed -i '1i @import "catppuccin-frappe"' ~/.config/rofi/catppuccin-default.rasi
touch ~/.config/rofi/config.rasi
echo "@theme 'catppuccin-default'" > ~/.config/rofi/config.rasi
mkdir ~/.config/autostart
cp xfce-config Plank.desktop Polybar.desktop ~/.config/autostart


