#!/bin/bash	


mkdir ~/.themes
mkdir ~/.local/share/icons
mkdir ~/Pictures/Wallpapers
mkdir ~/.fonts
git clone https://github.com/zayronxio/Zafiro-Nord-Dark
git clone https://github.com/EliverLara/Nordic
git clone https://github.com/yeyushengfan258/Future-cursors
wget https://github.com/EliverLara/Nordic/blob/master/extras/wallpapers/nordic-wall.jpg
wget https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip
mv Nordic ~/.themes
mv Zafiro-Nord-Dark ~/.local/share/icons
mv Future-cursors ~/.local/share/icons
mv nordic-wall.jpg ~/Pictures/Wallpapers
mkdir JetBrains
unzip JetBrainsMono-2.304.zip JetBrains/
cd JetBrains/fonts/ttf || exit
unzip FiraCode.zip
mv FiraCode*.* ~/.fonts
mv *.* ~/.fonts
